services:
  service-user:
    container_name: service-user
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      TZ: UTC
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
